name: Showpoint
options:
  bundleIdPrefix: io.stepanenko
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "0.1.3"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  Showpoint:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.stepanenko.Showpoint
        PRODUCT_NAME: Showpoint
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Oleksii Stepanenko"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        ENABLE_HARDENED_RUNTIME: NO
        DEAD_CODE_STRIPPING: YES
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: Showpoint.entitlements
      properties:
        com.apple.security.app-sandbox: false
